"""Wraps tools/modgen_preview.evox into the MCP tools/call body for evox_execute: one module generated by scripts/modgen.evox, spawned in Studio.
Usage: python gen_modules_preview.py KIND SEED [--at X Y Z] [--yaw DEG] [--up|--down] [--sun DEG] [--keep]
KIND = index into defs.kindFromIndex (0 central, 1 habitat, 2 hydroponics, 3 research, 4 medical, 5 storage, 6 battery, 7 fridge, 8 greenhouse,
9 junction, 10 solar wing, 11 radiator wing, 12 gas storage). --keep leaves the modules already spawned (default: clear the previous demo first)."""
import json, math, sys
from pathlib import Path
a = sys.argv
def arg(name, default, n=1):
    if name not in a: return default
    v = [float(x) for x in a[a.index(name) + 1:a.index(name) + 1 + n]]; return v[0] if n == 1 else v
x, y, z = arg('--at', [0.0, 0.0, 0.0], 3)
src = (Path(__file__).resolve().parent / 'modgen_preview.evox').read_text()
for k, v in (('$KIND', str(int(a[1]))), ('$SEED', str(int(a[2]))), ('$PX', '%.3f' % x), ('$PY', '%.3f' % y), ('$PZ', '%.3f' % z), ('$YAW', '%.4f' % math.radians(arg('--yaw', 0.0))),
             ('$SUN', '%.4f' % math.radians(arg('--sun', 128.0))), ('$CLEAR', 'false' if '--keep' in a else 'true'),
             ('$UPS', '0.70711' if '--up' in a else '-0.70711' if '--down' in a else '0.0'), ('$UPC', '0.70711' if '--up' in a or '--down' in a else '1.0')):
    src = src.replace(k, v)
print(json.dumps({'jsonrpc': '2.0', 'id': 1, 'method': 'tools/call', 'params': {'name': 'evox_execute', 'arguments': {'code': src}}}))
