"""Generates ui/hud.ui (in-game HUD, skinned with the sprites from the ui/flat/*.ltct recipes).
Run with any Python 3 (Blender's works):  "C:/Program Files/Blender Foundation/Blender 5.2/5.2/python/bin/python.exe" tools/gen_hud.py    (from the project root)
Ids must stay in sync with scripts/hud.evox. Layout: top resource bar, left navigation (MODULES / SYSTEMS / CREW / RESOURCES / RESEARCH / MISSIONS) with a side panel,
bottom build tray (category tabs + module cards), terminal-style info panel + time controls bottom right, toasts top right."""
from pathlib import Path
out = Path('ui/hud.ui'); L = []
import re
def w(s=''):
    m = re.search(r'(\[box [^\]]*\.hd[^\]]*\] \{ )([A-Z]+)( \})', s)
    if m: s = s[:m.start(2)] + ' '.join(m.group(2)) + s[m.end(2):]
    L.append(s)

w('''// In-game HUD, flat dark-glass skin (sprites from the ui/flat/*.ltct recipes). Texts, bars and visibility are driven by scripts/hud.evox through the element ids.
// GENERATED by tools/gen_hud.py - edit the generator, not this file. Sprites: ui/flat/*.spr (texture recipes), thumbnails ui/kit, icons ui/icons2.
[style] {
	.panel { bg-image: "ui/flat/panel.spr"; padding: 1.5em; color: #d5dbe0; }
	.panelb { bg-image: "ui/flat/panel.spr"; padding: 1.8em; color: #d5dbe0; }
	.term { bg-image: "ui/flat/panel_flat.spr"; padding: 1.1em; color: #9fe8c0; }
	.hd { color: #e8952a; font-size: 15; padding-bottom: 0.6em; }
	.navb { width: 9.5em; height: 2.6em; margin-bottom: 0.3em; padding-left: 1.4em; padding-top: 0.7em; font: "/engine/editor/fonts/Roboto-Bold.ttf"; font-size: 15; }
	.tab { height: 2.2em; margin-right: 0.3em; padding-top: 0.55em; align: center; font: "/engine/editor/fonts/Roboto-Bold.ttf"; font-size: 16; }
	.chip { padding-left: 0.5em; padding-right: 0.5em; direction: row; wrap: false; align-items: center; }
	.cl { font-size: 11; color: #8b97a3; }
	.cv { font-size: 19; color: #f1efe6; }
	.btn { bg-image: "ui/flat/btn.spr"; padding: 0.55em; margin: 0.1em; align: center; color: #e3e9ee; }
	.btn:hover { bg-image: "ui/flat/btn_h.spr"; color: #ffe2b8; }
	.btnon { bg-image: "ui/flat/btn_on.spr"; padding: 0.55em; margin: 0.1em; align: center; color: #fff1dc; }
	.tbtn { bg-image: "ui/flat/btn.spr"; padding: 0.3em; margin: 0.12em; }
	.tbtn:hover { bg-image: "ui/flat/btn_h.spr"; }
	.card { bg-image: "ui/flat/card.spr"; padding: 0.6em; margin: 0.2em; width: 11.6em; color: #dbe3ea; }
	.card:hover { bg-image: "ui/flat/card_h.spr"; }
	.cname { color: #f1efe6; font-size: 17; padding-top: 0.2em; padding-bottom: 0.3em; }
	.cost { padding-right: 0.4em; font-size: 14; color: #9fb0bf; direction: row; wrap: false; align-items: center; }
	.cstat { font-size: 14; color: #e8952a; padding-top: 0.35em; }
	.acard { bg-image: "ui/flat/card.spr"; padding: 0.35em; margin: 0.2em; width: 21.4em; color: #dbe3ea; }
	.acard:hover { bg-image: "ui/flat/card_h.spr"; }
	.ccard { bg-image: "ui/flat/card.spr"; padding: 0.3em; margin: 0.1em; width: 6.3em; color: #dbe3ea; }
	.ccard:hover { bg-image: "ui/flat/card_h.spr"; }
	.lrow { bg-image: "ui/flat/card.spr"; padding: 0.4em; padding-left: 0.5em; margin-bottom: 0.2em; width: 32.2em; color: #dbe3ea; }
	.lrow:hover { bg-image: "ui/flat/card_h.spr"; }
	.lcost { padding-right: 0.8em; font-size: 14; color: #9fb0bf; direction: row; wrap: false; align-items: center; }
	.gh { font-size: 12; color: #8b97a3; padding-top: 0.5em; padding-bottom: 0.3em; }
	.stab { height: 2em; margin-right: 0.25em; padding-top: 0.45em; align: center; font: "/engine/editor/fonts/Roboto-Bold.ttf"; font-size: 14; }
	.mitem { bg-image: "ui/flat/menu_none.spr"; padding: 0.45em; padding-left: 1.6em; margin-bottom: 0.2em; color: #dbe3ea; font-size: 32; width: 20em; }
	.mitem:hover { bg-image: "ui/flat/menu_hover.spr"; color: #ffd9a0; }
	.acost { padding-right: 0.2em; font-size: 10; direction: row; wrap: false; align-items: center; }
	.bar { bg-color: #121a22; height: 0.4em; width: 21.4em; margin-bottom: 0.4em; }
	.ck { width: 1.3em; height: 1.3em; bg-image: "ui/flat/btn.spr"; margin-right: 0.8em; margin-top: 0.15em; }
	.ckon { width: 1.3em; height: 1.3em; bg-image: "ui/kit/ic_check.spr"; margin-right: 0.8em; margin-top: 0.15em; }
	.ot { color: #edf0f2; font-size: 18; }
	.os { color: #98a3ac; font-size: 15; padding-top: 0.2em; padding-bottom: 0.7em; }
	.row { font-size: 16; padding-bottom: 0.25em; }
	.toast { margin-bottom: 0.35em; }
	.tin { direction: row; wrap: false; align-items: center; padding: 0.55em; padding-left: 1em; }
	.tic { width: 2em; height: 2em; margin-right: 0.7em; }
	.ttx { width: 21em; }
	.tn { width: 19em; height: 6.6em; padding: 0.4em; }
	.tnl { bg-image: "ui/flat/node_l.spr"; }
	.tna { bg-image: "ui/flat/node_a.spr"; }
	.tnu { bg-image: "ui/flat/node_u.spr"; }
	.tnx { bg-image: "ui/flat/node_x.spr"; }
}

[box $hud width=100% height=100% font="/engine/editor/fonts/Roboto-Light.ttf" font-size=18 color=#d5dbe0] {
// ================= top bar =================''')
w('[box $topbar position=absolute left=0 top=0 width=100% height=3.6em direction=row wrap=false align-items=center bg-color=#010203f2 padding-left=1.2em padding-right=1.2em] {')
w('\t[box width=13em] {')
w('\t\t[box direction=row wrap=false font-size=22 color=#f0eadb] { [box padding-right=0.55em] { S T I L L } [box] { A B O V E } }')
w('\t\t[box direction=row wrap=false font-size=10 color=#e6ac3c padding-top=0.3em] { [box padding-right=0.7em] { O R B I T A L } [box] { R E F U G E } }')
w('\t}')
def badge(text, size): return '[span font="/engine/editor/fonts/Roboto-Bold.ttf" font-size=%d color=#3aa8e8 text="%s"]' % (size, text)
w('\t[box direction=row wrap=false grow=1 align-items=center justify-content=space-between] {')
for icon, label, cid in (('steel', 'STEEL', 'c_steel'), ('polymers', 'POLYMERS', 'c_poly'), ('electronics', 'ELECTRONICS', 'c_elec'), ('parts', 'PARTS', 'c_parts'),
                         ('food', 'FOOD', 'c_food'), ('water', 'WATER', 'c_water'), ('oxygen', 'OXYGEN', 'c_o2'), ('co2', 'CO2', 'c_co2'), ('power', 'POWER', 'c_power'), ('altitude', 'ALTITUDE', 'c_alt'), ('crew', 'CREW', 'c_crew'), ('research', 'RESEARCH', 'c_rp')):
    pic = ('[box width=2.1em height=2.1em padding-top=0.35em] { %s }' % badge(icon[4:], 17)) if icon.startswith('txt:') else '[box width=2.1em height=2.1em bg-image="ui/icons2/cut_%s.spr"] {}' % icon
    w('\t\t[box .chip] { %s [box padding-left=0.55em] { [box .cl] { %s } [box .cv] { [span $%s text=" "] } } }' % (pic, label, cid))
    if cid != 'c_rp': w('\t\t[box width=0.07em height=2.4em bg-color=#1f2a36] {}')
w('\t}')
w('\t[box width=0.07em height=2.4em bg-color=#1f2a36 margin-left=0.6em] {}')
w('\t[box direction=row wrap=false align-items=center padding-left=1em] {')
for act, ic in (('speed0', 't_pause'), ('speed1', 't_play'), ('speed2', 't_ff'), ('speed3', 't_fff')):
    w('\t\t[box .tbtn on-click=%s] { [box bg-image="ui/icons2/%s.spr" width=1.3em height=1.3em] {} }' % (act, ic))
w('\t\t[box .btn on-click=menu_open margin-left=0.8em width=4.4em font-size=13] { MENU }')
w('\t}')
w('}')
w('[box position=absolute left=0 top=3.6em width=100% height=0.12em bg-color=#1d2733] {}')
w('')
w('// ================= top centre: active tasks (hud.evox tasksPanel): who works on what, with progress =================')
w('[box $tasks .panel position=absolute left=50% pivot-x=50% top=97% pivot-y=100% width=30em font-size=14 padding=0.9em direction=column visible=false] {')
w('	[box .hd font-size=12 padding-bottom=0.4em] { TASKS }')
for k in range(1, 9):
    w('	[box $tk_%d width=28em padding-bottom=0.5em visible=false] { [box width=28em] { [span $tk_t_%d color=#dbe3ea text=" "] } [box width=28em height=0.25em bg-color=#0b1218 margin-top=0.2em] { [box $tk_b_%d width=0%% height=0.25em bg-color=#e8952a] {} } }' % (k, k, k))
w('}')
w('')
w('// ================= left: navigation, objectives =================')
w('[box $nav position=absolute left=0.8em top=4.5em direction=column] {')
# plates without their baked labels: the label is drawn in the game font, sharp at any UI scale
# 0..3 open the build list on one category (hud.evox navToggle sets st.tab), the rest open their side panels
for i, name in enumerate(('STRUCTURE', 'EXTENSIONS', 'RACKS', 'ATTACHMENTS', 'CREW', 'RESOURCES', 'RESEARCH', 'OBJECTIVES')):
    gap = ' margin-top=0.9em' if i == 4 else ''
    w('\t[box $nav_%d .navb on-click=nav%d%s bg-image="ui/flat/navb.spr"] { [span color=#c6d0da text="%s"] }' % (i, i, gap, name))
    w('\t[box $nava_%d .navb on-click=nav%d%s bg-image="ui/flat/navb_a.spr" visible=false] { [span color=#ffffff text="%s"] }' % (i, i, gap, name))
w('}')
w('')
w('// ================= side panel next to the navigation (one per nav item) =================')
w('[box $p_crew .panel position=absolute left=12.6em top=4.5em width=51em visible=false font-size=16 direction=row wrap=false] {')
# left column: summary and the roster - one row per crew slot (scripts/config.evox CREW_MAX, hud.evox crewRoster), dead ones stay listed. Name and status have
# one span per colour (spans cannot change colour at runtime): normal / selected / dead, aboard / away / dead. A click on a row selects that member
w('[box width=47em direction=column padding-right=1.5em] {')
w('\t[box .hd] { CREW }')
for k in range(1, 4): w('\t[box .row width=44em] { [span $cr_%d text=" "] }' % k)
STATS = ('STR', 'INT', 'DEX', 'END')   # scripts/config.evox STAT_* order; a stat cell is amber from 7 up (hud.evox shows one of two spans)
w('\t[box direction=row wrap=false padding-top=0.4em padding-bottom=0.2em font-size=14] { [box width=6.4em] { [span color=#8f9ba4 font-size=12 text="NAME"] } [box width=5.4em] { [span color=#8f9ba4 font-size=12 text="STATUS"] } %s [box padding-left=0.6em] { [span color=#8f9ba4 font-size=12 text="DOING"] } }'
  % (' '.join('[box width=2.3em] { [span color=#8f9ba4 font-size=12 text="%s"] }' % n for n in STATS) + ' [box width=3.2em] { [span color=#8f9ba4 font-size=12 text="FIT"] }'))
for k in range(1, 25):
    w('\t[box $crr_%d on-click=crsel_%d direction=row wrap=false visible=false padding-bottom=0.15em font-size=14] {' % (k, k))
    w('\t\t[box width=6.4em] { [span $crn_%d color=#f1efe6 text=" "] [span $crns_%d color=#e6ac3c text=" " visible=false] [span $crnd_%d color=#6b747b text=" " visible=false] }' % (k, k, k))
    w('\t\t[box width=5.4em] { [span $crs_%d color=#9fe8a8 text=" "] [span $crsa_%d color=#e6ac3c text=" " visible=false] [span $crsd_%d color=#6b747b text=" " visible=false] }' % (k, k, k))
    for i in range(4): w('\t\t[box width=2.3em] { [span $crv%d_%d color=#8f9ba4 text=" "] [span $crvh%d_%d color=#e6ac3c text=" " visible=false] }' % (i, k, i, k))
    w('\t\t[box width=3.2em] { [span $crf_%d color=#9fe8a8 text=" "] [span $crfl_%d color=#ff7a6a text=" " visible=false] }' % (k, k))   # fitness, red when low
    w('\t\t[box width=0.6em] {}')
    w('\t\t[box width=21em] { [span $crd_%d color=#c9d1d7 text=" "] }' % k)
    w('\t}')
w('}')
w('}')   # p_crew
# missions panel
# objectives panel (hud.evox objectivesPanel): the active objectives of scripts/objectives.evox, up to 10 rows, then the win goal
w('[box $p_obj .panel position=absolute left=12.6em top=4.5em width=46em visible=false font-size=16 direction=column] {')
w('\t[box .hd] { OBJECTIVES }')
for k in range(1, 11):
    w('\t[box $orow_%d direction=column visible=false padding-bottom=0.6em] {' % k)
    w('\t\t[box direction=row wrap=false align-items=center] { [box width=32em] { [span $ot_%d color=#e6ac3c text=" "] } [box $oc_%d .btn on-click=claim%d visible=false padding=0.2em padding-left=0.9em padding-right=0.9em font-size=13] { CLAIM } }' % (k, k, k))
    w('\t\t[box width=42em] { [span $oh_%d color=#c9d1d7 font-size=14 text=" "] }' % k)
    w('\t\t[box width=42em] { [span $ol_%d color=#8f9ba4 font-size=13 text=" "] }' % k)
    w('\t}')
w('\t[box] { [span $obj_more color=#8f9ba4 font-size=14 text=" "] }')
w('\t[box .hd padding-top=0.8em] { GOAL }')
w('\t[box] { [span $obj_goal color=#c9d1d7 font-size=14 text=" "] }')
# radar contacts (hud.evox missionsPanel): up to scripts/config.evox CONTACT_MAX open ones with launch / ignore, then up to MISSION_MAX missions under way.
# The requirement line has a ready (green) and a blocked (red) span, the script shows one
w('\t[box .hd padding-top=1em] { MISSIONS }')
w('\t[box] { [span $ms_radar color=#c9d1d7 text=" "] }')
w('\t[box] { [span $ms_ships color=#8f9ba4 font-size=14 text=" "] }')
w('\t[box $mc_none visible=false] { [span color=#8f9ba4 font-size=14 text="Listening... no contacts yet."] }')
for k in range(1, 5):
    w('\t[box $mc_%d direction=column visible=false padding-top=0.5em] {' % k)
    w('\t\t[box] { [span $mc_t_%d color=#e6ac3c text=" "] }' % k)
    w('\t\t[box width=42em] { [span $mc_d_%d color=#f1efe6 font-size=14 text=" "] }' % k)
    w('\t\t[box width=42em] { [span $mc_c_%d color=#a9b3ba font-size=14 text=" "] }' % k)
    w('\t\t[box] { [span $mc_ok_%d color=#9fe8a8 font-size=14 text=" "] [span $mc_no_%d color=#ff7a6a font-size=14 text=" " visible=false] }' % (k, k))
    w('\t\t[box direction=row] { [box .btn width=8em on-click=mlaunch_%d] { Launch } [box .btn width=6em on-click=mignore_%d] { Ignore } }' % (k, k))
    w('\t}')
for k in range(1, 5): w('\t[box $mmr_%d visible=false] { [span $mm_%d color=#78e6ae font-size=14 text=" "] }' % (k, k))
w('}')
# always-visible next objective (hud.evox nextObjective), bottom left; hidden while the OBJECTIVES panel is open
w('[box $nextobj .panel position=absolute left=0.8em top=99% pivot-y=100% width=36em direction=column visible=false font-size=16] {')
w('\t[box .hd] { NEXT OBJECTIVE }')
w('\t[box width=33em] { [span $no_t color=#e8952a font-size=18 text=" "] }')
w('\t[box width=33em] { [span $no_h color=#c9d1d7 font-size=14 text=" "] }')
w('\t[box width=33em] { [span $no_l color=#8f9ba4 font-size=13 text=" "] }')
w('}')
# resource table: one row per resource, cells filled by hud.evox (resourcesPanel). Net and status have a normal (green / grey) and a warning (red)
# span, the script shows one of them (spans cannot change colour at runtime). Rows with a capacity get a fill bar under the stock
RES_ROWS = ((15, 'cut_mixed', 'Mixed salvage', True), (1, 'cut_steel', 'Steel', False), (2, 'cut_electronics', 'Electronics', False), (3, 'cut_polymers', 'Polymers', False), (4, 'cut_parts', 'Machine parts', False), None,
            (5, 'cut_oxygen', 'Oxygen', True), (16, 'cut_water', 'Water', True), (12, 'cut_co2', 'CO2', True), (6, 'cut_food', 'Food', True), None,
            (7, 'cut_power', 'Power', False), (8, 'cut_battery', 'Battery', True), (9, 'cut_heat', 'Heat', False), None,
            (13, 'cut_fuel', 'Fuel', True), (14, 'cut_altitude', 'Altitude', True), None,
            (10, 'cut_research', 'Research', False), (11, 'cut_crew', 'Crew', True))
COLS = (('STOCK', 10.4), ('IN', 7.6), ('OUT', 7.6), ('NET', 7.6))
w('[box $p_res .panel position=absolute left=12.6em top=4.5em width=72em visible=false font-size=15] {')
w('\t[box .hd] { RESOURCES }')
w('\t[box direction=row wrap=false padding-bottom=0.4em] { [box width=10.3em] { [span color=#8f9ba4 font-size=12 text="RESOURCE"] } %s [box] { [span color=#8f9ba4 font-size=12 text="STATUS"] } }'
  % ' '.join('[box width=%.1fem] { [span color=#8f9ba4 font-size=12 text="%s"] }' % (wem, name) for name, wem in COLS))
for row in RES_ROWS:
    if row is None:
        w('\t[box width=59.6em height=0.08em bg-color=#1c2228 margin-top=0.25em margin-bottom=0.45em] {}'); continue
    r, icon, name, has_bar = row
    w('\t[box direction=row wrap=false align-items=center padding-bottom=0.3em] {')
    if icon.startswith('txt:'): w('\t\t[box width=1.6em height=1.6em margin-right=0.5em padding-top=0.3em] { %s }' % badge(icon[4:], 10 if len(icon) > 7 else 11))
    else: w('\t\t[box width=1.6em height=1.6em bg-image="ui/icons2/%s.spr" bg-fit=contain margin-right=0.5em] {}' % icon)
    w('\t\t[box width=8.2em] { [span color=#edf0f2 text="%s"] }' % name)
    bar = ' [box width=85%% height=0.25em bg-color=#0b1218 margin-top=0.15em] { [box $rs_b_%d width=0%% height=0.25em bg-color=#6fb7d9] {} }' % r if has_bar else ''
    w('\t\t[box width=10.4em] { [box] { [span $rs_s_%d color=#f1efe6 text=" "] }%s }' % (r, bar))
    w('\t\t[box width=7.6em] { [span $rs_i_%d color=#a9d8b0 text=" "] }' % r)
    w('\t\t[box width=7.6em] { [span $rs_o_%d color=#d9b0a9 text=" "] }' % r)
    w('\t\t[box width=7.6em] { [span $rs_np_%d color=#9fe8a8 text=" "] [span $rs_nm_%d color=#ff7a6a text=" " visible=false] }' % (r, r))
    w('\t\t[box width=23em] { [span $rs_st_%d color=#a9b3ba text=" "] [span $rs_sw_%d color=#ff9a80 text=" " visible=false] }' % (r, r))
    w('\t}')
w('\t[box width=64em padding-top=0.4em] { [span $rs_foot color=#a9b3ba text=" "] }')
w('}')
# technology tree (hud.evox techTree, scripts/config.evox techStats): four branch lanes, prerequisites drawn as elbow connectors, columns = depth. Node ids are the tech ids
# 1..20; (column, row) below and the PREREQ table have to match the prerequisites in scripts/config.evox. A node has four variants (tnl_ locked / tna_ available /
# tnx_ being researched / tnu_ researched, each with name tnn?_, cost tc?_ and effect te?_ spans), the script shows one. A connector is a dim line plus a lit copy
# (ea_/eb_/ec_<node>_<k>: out of prerequisite k, the vertical bus, into the node); the script lights it once that prerequisite is researched. A click = tech<id>
NW, NH, PITCH, SUB = 19.0, 6.6, 21.0, 7.1
LANE_H = 15.6
LANE_NAMES = ('SURVIVAL AND MEDICINE', 'POWER AND THERMAL', 'SALVAGE AND MISSIONS', 'ORBIT AND STATION')
POS = {21: (0, 0), 2: (0, 1), 29: (1, 0), 3: (1, 1), 1: (2, 0), 4: (2, 1), 22: (3, 0), 24: (3, 1), 23: (4, 0), 5: (4, 1),
       6: (0, 0), 7: (0, 1), 25: (1, 1), 8: (2, 1), 9: (3, .5), 10: (4, .5),
       26: (0, 0), 12: (0, 1), 11: (1, 0), 13: (1, 1), 14: (2, .5), 27: (3, 0), 15: (3, 1), 28: (4, 1),
       16: (0, 1), 17: (2, 1), 18: (1, 0), 19: (3, 1), 20: (4, .5), 30: (0, 0), 31: (1, 1)}
LANE_OF = {n: 0 for n in (1, 2, 3, 4, 5, 21, 22, 23, 24, 29)}
LANE_OF.update({n: 1 for n in (6, 7, 8, 9, 10, 25)})
LANE_OF.update({n: 2 for n in (11, 12, 13, 14, 15, 26, 27, 28)})
LANE_OF.update({n: 3 for n in (16, 17, 18, 19, 20, 30, 31)})
PREREQ = {3: (2,), 4: (3,), 5: (22,), 8: (25,), 9: (6, 8), 10: (9,), 11: (26,), 13: (12,), 14: (11, 13), 18: (30,), 19: (17,), 20: (18, 19), 31: (30,), 23: (22,), 25: (7,), 28: (15,), 29: (21,)}
def node_xy(n):
    col, row = POS[n]; lane = LANE_OF[n]
    return col * PITCH, lane * LANE_H + 1.8 + row * SUB
dim, lit = '#1c2631', '#e8952a'
LW = 0.22
def line(x, y, wd, ht, cid, color): return '\t\t[box %sposition=absolute left=%.2fem top=%.2fem width=%.2fem height=%.2fem bg-color=%s%s] {}' % ('$%s ' % cid if cid else '', x, y, wd, ht, color, ' visible=false' if cid else '')
dimw, litw = [], []
for n, reqs in sorted(PREREQ.items()):
    xl, yl = node_xy(n)
    for k, r in enumerate(reqs):
        xr, yr = node_xy(r); xr += NW
        ya, yb = yr + NH / 2, yl + NH / 2
        bx = xl - 1.5
        segs = [('ea_%d_%d' % (n, k), xr, ya - LW / 2, bx - xr + LW, LW)]
        if abs(ya - yb) > 0.01: segs.append(('eb_%d_%d' % (n, k), bx, min(ya, yb) - LW / 2, LW, abs(ya - yb) + LW))
        segs.append(('ec_%d_%d' % (n, k), bx, yb - LW / 2, xl - bx, LW))
        for cid, x, y, wd, ht in segs:
            dimw.append(line(x, y, wd, ht, None, dim)); litw.append(line(x, y, wd, ht, cid, lit))
w('[box $p_rsch .panel position=absolute left=12.6em top=4.5em width=%.1fem visible=false font-size=16] {' % (4 * PITCH + NW + 5.5))
w('\t[box .hd] { TECHNOLOGY }')
w('\t[box .row] { [span $rp_line text=" "] }')
w('\t[box width=80em] { [span $tt_next color=#e6ac3c font-size=14 text=" "] }')
w('\t[box .bar width=%.1fem margin-top=0.3em] { [box $tt_bar width=0%% height=0.4em bg-color=#e6ac3c] }' % (4 * PITCH + NW))
leg = ''.join('[box width=1em height=1em bg-color=%s margin-right=0.4em] {} [box width=9em] { [span color=%s text="%s"] }' % (bg, fg, name)
              for bg, fg, name in (('#021409', '#9fe8a8', 'RESEARCHED'), ('#1f1401', '#e6ac3c', 'RESEARCHING'), ('#040c14', '#cfe3f2', 'AVAILABLE'), ('#010204', '#8f9ba4', 'LOCKED')))
w('\t[box direction=row wrap=false font-size=12 padding-bottom=0.3em] { %s }' % leg)
w('\t[box width=%.1fem height=%.1fem] {' % (4 * PITCH + NW + 1, 4 * LANE_H + 0.5))
for li, name in enumerate(LANE_NAMES):
    w('\t\t[box position=absolute left=0em top=%.2fem] { [span color=#8f9ba4 font-size=12 text="%s"] }' % (li * LANE_H + 0.3, name))
for l in dimw + litw: w(l)
STATE = (('l', '#6b747b', '#8f9ba4'), ('a', '#dcecf8', '#a9bccb'), ('x', '#e6ac3c', '#d9c9a0'), ('u', '#9fe8a8', '#c9d1d7'))
for n in sorted(POS):
    x, y = node_xy(n)
    w('\t\t[box position=absolute left=%.2fem top=%.2fem width=%.1fem height=%.1fem] {' % (x, y, NW, NH))
    for st, c1, c2 in STATE:
        w('\t\t\t[box $tn%s_%d .tn .tn%s on-click=tech%d%s] { [box width=18em] { [span $tnn%s_%d color=%s font-size=22 text=" "] } [box width=18em] { [span $tc%s_%d color=%s font-size=16 text=" "] } [box width=18em] { [span $te%s_%d color=%s font-size=16 text=" "] } }'
          % (st, n, st, n, ' visible=false' if st != 'l' else '', st, n, c1, st, n, c1, st, n, c2))
    w('\t\t}')
w('\t}')
w('}')
w('')
w('// ================= top right: alerts and log =================')
w('[box $toasts position=absolute left=99% pivot-x=100% top=4.5em width=25em direction=column font-size=15] {')
def toast(tid, accent, icon, inner):
    w('\t[box $%s .toast bg-image="%s" visible=false] { [box .tin] { [box .tic bg-image="ui/icons2/%s.spr"] {} [box .ttx] { %s } } }' % (tid, accent, icon, inner))
RED, AMBER, BLUE, GREEN = 'ui/flat/toast_red.spr', 'ui/flat/toast_amber.spr', 'ui/flat/toast_blue.spr', 'ui/flat/toast_green.spr'   # bg-color comes out lighter on screen than its hex value
for tid, accent, icon, txt in (('al_o2', RED, 'alert_low_oxygen', 'Low oxygen - build life support'), ('al_co2', RED, 'alert_low_oxygen', 'CO2 too high - build scrubbers or plants'), ('al_food', RED, 'alert_low_food', 'Low food - build hydroponics'),
                               ('al_power', RED, 'alert_no_power', 'Power failure - output reduced'), ('al_heat', AMBER, 'alert_repair', 'Overheating - add radiators')):
    toast(tid, accent, icon, '[span color=#f3e4e0 text="%s"]' % txt)
toast('al_water', RED, 'alert_low_oxygen', '[span color=#f3e4e0 text="Low water - recycle it, fetch ice"]')
toast('al_hp', AMBER, 'alert_repair', '[span $al_hp_t color=#efe6cc text=" "]')
toast('al_orbit', RED, 'alert_no_power', '[span $al_orbit_t color=#f3e4e0 text=" "]')
toast('al_fit', AMBER, 'alert_crew', '[span $al_fit_t color=#efe6cc text=" "]')
toast('al_rescue', BLUE, 'alert_crew', '[span $al_rescue_t color=#d9e6f0 text=" "]')
toast('lg_2', 'ui/flat/toast_dark.spr', 'alert_ok', '[span $l_2 color=#8fa8bf text=" "]')
toast('lg_1', 'ui/flat/toast_dark.spr', 'alert_ok', '[span $l_1 color=#b4cbe0 text=" "]')
toast('lg_0', GREEN, 'alert_ok', '[span $l_0 color=#ffffff text=" "]')
w('}')
w('')
w('// ================= left: build list (a header, then one small row per module / rack / attachment; cost and effect in the tooltip) =================')
w('[box $buildbar .panel position=absolute left=12.6em top=4.5em width=35em direction=column] {')
w('\t[box .hd] { [span $bld_hd color=#e8952a text=" "] }')
def build_row(card, pre, n, action, thumb):
    """ids as hud.evox expects them: <card>_n, <pre>thumb_n, <pre>nb_n / <pre>name_n, <pre>sb_n / <pre>st_n; the cost is in the hover tooltip (tip_cost)"""
    w('\t\t[box $%s_%d .lrow on-click=%s_%d visible=false direction=row wrap=false align-items=center] {' % (card, n, action, n))
    w('\t\t\t[box $%sthumb_%d %s] {}' % (pre, n, thumb))
    w('\t\t\t[box $%snb_%d width=17em] { [span $%sname_%d color=#f1efe6 font-size=16 text=" "] }' % (pre, n, pre, n))
    w('\t\t\t[box $%ssb_%d] { [span $%sst_%d color=#e8952a font-size=13 text=" "] }' % (pre, n, pre, n))
    w('\t\t}')
w('\t[box direction=column padding-top=0.6em] {')
# modules (defs.kindFromIndex order); only the cards of the current tab are shown
for n in range(1, 9):
    build_row('card', 'c', n, 'build', 'bg-image="ui/kit/th_%d.spr" width=3.7em height=2.2em margin-right=0.8em' % n)
w('\t}')
# racks, in groups (headers are always shown with the list)
w('\t[box $rrows direction=column padding-top=0.4em visible=false] {')
for head, ids in (('LIFE SUPPORT', (1, 2, 3, 13, 11, 12)), ('FOOD AND STORAGE', (4, 5, 6, 7)), ('INDUSTRY', (8, 9, 10, 14))):
    w('\t\t[box .gh] { %s }' % head)
    for n in ids: build_row('rcard', 'r', n, 'rbuild', 'bg-image="ui/icons2/rack_%d.spr" width=2.2em height=2.2em margin-left=0.75em margin-right=0.75em' % n)
w('\t}')
w('\t[box $arows direction=column padding-top=0.4em visible=false] {')
for head, ids in (('SYSTEMS', (1, 2, 11, 6, 7)), ('STORAGE', (3, 4, 5)), ('COMMS', (8, 9, 10))):
    w('\t\t[box .gh] { %s }' % head)
    for n in ids: build_row('acard', 'a', n, 'abuild', 'bg-image="ui/icons2/att_%d.spr" width=2.2em height=2.2em margin-left=0.75em margin-right=0.75em' % n)
w('\t}')
w('\t[box $build_empty width=33em visible=false] { [span $b_empty color=#b9c3cb font-size=14 text=" "] }')
w('}')
w('')
w('// ================= bottom right: info terminal and time =================')
w('// ================= right: selected module =================')
w('[box $modinfo .panel position=absolute left=99% pivot-x=100% top=50% pivot-y=50% width=23em direction=column visible=false font-size=15] {')
w('\t[box direction=row wrap=false] { [box width=18.2em] { [span $mi_title color=#e6ac3c font-size=17 text=" "] } [box .btn on-click=mclose width=1.8em] { x } }')
w('\t[box width=19.4em padding-bottom=0.3em] { [span $mi_hp color=#f1efe6 text=" "] [span $mi_hp_bad color=#ff7a6a text=" " visible=false] }')
w('\t[box .bar width=19.4em] { [box $mi_bar width=100% height=0.4em bg-color=#6fb7d9] }')
w('\t[box $mi_task width=19.4em visible=false] { [span $mi_task_t color=#e6ac3c text=" "] }')
for k in range(1, 13): w('\t[box $mi_r%d .row width=19.4em] { [span $mi_l%d color=#c9d1d7 text=" "] }' % (k, k))
w('\t[box .btn on-click=mrepair margin-top=0.4em] { [span $mi_repair text="Repair module"] }')
w('\t[box $mi_boost .btn on-click=boost visible=false] { [span $mi_boost_t text="Reboost"] }')
w('\t[box $mi_dis .btn on-click=mdismantle visible=false] { [span $mi_dis_t text="Dismantle"] }')
w('\t[box $mi_ship .btn on-click=mship visible=false] { [span $mi_ship_t text="Build shuttle"] }')
w('\t[box $rk_free width=19.4em padding-top=0.5em visible=false] { [span $rk_free_t color=#e6ac3c text=" "] }')
for k in range(1, 11): w('\t[box $rk_%d direction=row wrap=false align-items=center visible=false] { [box width=7.4em] { [span $rk_t_%d color=#c9d1d7 text=" "] } [box $rkj_%d .btn on-click=rkjob_%d width=3.2em visible=false] { [span $rkj_t_%d text="sort"] } [box $rks_%d .btn on-click=rkstaff_%d width=4.4em] { [span $rks_t_%d text="staff"] } [box .btn on-click=rkdis_%d width=4.6em] { remove } }' % (k, k, k, k, k, k, k, k, k))
w('}')
w('[box $tip .term position=absolute left=49.6em top=4.5em width=26em direction=column visible=false font-size=18] {')
w('\t[box width=23.4em] { [span $tip_title color=#a8ffd2 font-size=17 text=" "] }')
w('\t[box width=23.4em] { [span $tip_desc color=#78e6ae text=" "] }')
w('\t[box width=23.4em padding-top=0.5em] { [span $tip_fx color=#e6ac3c text=" "] }')
w('\t[box width=23.4em padding-top=0.5em] { [span $tip_cost color=#dfe6ec text=" "] }')
w('}')
w('')
w('// ================= centre: game over / victory =================')
w('[box $banner .panelb position=absolute left=50% pivot-x=50% top=45% pivot-y=50% width=34em align=center visible=false font-size=22] {')
w('\t[box] { [span $banner_text text=" "] }')
w('\t[box $restart_btn .btnon width=14em on-click=restart visible=false] { Restart station }')
w('}')
w('')
w('// ================= crew choice popup (hud.evox askCrew): every order that needs someone asks who =================')
w('[box $crewpick .panelb position=absolute left=50% pivot-x=50% top=28% width=21em font-size=16 direction=column visible=false] {')
w('	[box .hd] { ASSIGN }')
for k in range(1, 13):
    w('	[box $pk_%d .btn on-click=pick%d width=16.6em visible=false] { [box] { [span $pk_n_%d font-size=18 color=#f1efe6 text=" "] [span $pk_t_%d font-size=13 color=#8b97a3 text=" "] } [box padding-top=0.15em] { [span $pk_s_%d font-size=12 color=#e6ac3c text=" "] } }' % (k, k, k, k, k))
w('	[box $pk_none visible=false padding-bottom=0.5em] { [span color=#ff7a6a text="Nobody is free."] }')
w('	[box .btn on-click=pickcancel width=16.6em margin-top=0.6em color=#8b97a3] { CANCEL }')
w('}')
w('')
w('// ================= centre of the screen: why an order failed (hud.evox g_result), fades after a few seconds =================')
w('[box $center_msg .panel position=absolute left=50% pivot-x=50% top=40% padding=1em padding-left=2em padding-right=2em visible=false] { [span $center_msg_t font-size=22 color=#ff9a80 text=" "] }')
w('')
w('// ================= main menu (hud.evox menu*): covers everything, the game is paused while it is open =================')
w('[box $menu position=absolute left=0 top=0 width=100% height=100% bg-image="ui/flat/menu_grad.spr" visible=false] {')
w('\t[box position=absolute left=9em top=12em width=56em direction=column] {')
w('\t\t[box direction=row wrap=false font-size=96 color=#f4efe3] { [box padding-right=0.35em] { [span font="/engine/editor/fonts/Roboto-Bold.ttf" text="STILL"] } [box] { [span font="/engine/editor/fonts/Roboto-Light.ttf" text="ABOVE"] } }')
w('\t\t[box width=3.2em height=0.1em bg-color=#e8952a margin-top=0.2em margin-bottom=0.7em] {}')
w('\t\t[box direction=row wrap=false font-size=22 color=#e8952a padding-bottom=0.6em] { [box padding-right=0.9em] { [span text="O R B I T A L"] } [box] { [span text="R E F U G E"] } }')
w('\t\t[box width=36em padding-bottom=3.6em] { [span font-size=20 color=#9aa6b2 text="The Earth below is dead. One damaged module, two crew, and a few hours of air."] }')
w('		[box $mn_continue .mitem on-click=menu_continue] { [span color=#6b7682 text="Continue"] }')
w('\t\t[box $mn_start .mitem on-click=menu_start] { [span text="Start game"] }')
w('\t\t[box $mn_resume .mitem on-click=menu_start visible=false] { [span text="Resume"] }')
w('\t\t[box $mn_new .mitem on-click=menu_new visible=false] { [span text="New game"] }')
w('\t\t[box .mitem on-click=menu_controls] { [span text="Controls"] }')
w('\t\t[box $mn_help width=40em padding-top=1.2em padding-left=1.6em visible=false direction=column font-size=18 color=#c0cad3] {')
for line in ('Right mouse drag: orbit the camera.   Wheel: zoom.   WASD: pan.',
             'Left nav: pick STRUCTURE, EXTENSIONS, RACKS or ATTACHMENTS, click an item, then click a free port or hull slot.',
             'R turns the item being placed. Esc or a right click cancels. Esc with nothing selected opens this menu.',
             'Give an order: every job needs someone, and a popup asks who.',
             'Space pauses. Z / X / C = 1x / 3x / 10x. B starts a reboost burn.',
             'Keep the crew breathing, fed and watered, and keep the orbit up. The OBJECTIVES tab lists what is wrong.'):
    w('\t\t\t[box width=40em padding-bottom=0.5em] { [span text="%s"] }' % line)
w('\t\t}')
w('\t}')
w('\t[box position=absolute left=7em top=96% pivot-y=100% font-size=16 color=#7a8794] { [span text="Esc: menu    Space: pause    Z X C: speed"] }')
w('}')
w('} // full-canvas HUD')
out.write_text('\n'.join(L) + '\n'); print('generated', out)
