#!/bin/bash
# Drives the running Studio through its remote plugin (http://127.0.0.1:17123/mcp): game input, screenshots as PNG, module previews.
# Usage: tools/parts_demo.sh module KIND SEED [--at X Y Z] [--yaw DEG] [--keep]   (a module generated by scripts/modgen.evox, see gen_modules_preview.py)
#        tools/parts_demo.sh key <KEY> | click <x> <y> [left|right|middle] | input '<send_input arguments as JSON>'     (input for the running game; x, y = game view pixels at full size)
#        tools/parts_demo.sh play | stop | gameshot <name> [scale]      (start / stop game mode, screenshot of the game view -> screenshots/<name>.png)
#        tools/parts_demo.sh shot <name> [scale]      (screenshot of the scene view -> screenshots/<name>.png)
B="/c/Program Files/Blender Foundation/Blender 5.2"; PY="$B/5.2/python/bin/python.exe"; cd "$(dirname "$0")/.."
call() { curl -s -m 60 -X POST http://127.0.0.1:17123/mcp -H "Content-Type: application/json" -d "$1"; echo; }
case "$1" in
 module) "$PY" tools/gen_modules_preview.py "${@:2}" > screenshots/_demo_req.json && call @screenshots/_demo_req.json | cut -c1-900; rm -f screenshots/_demo_req.json ;;
 play)  call '{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"start_game","arguments":{}}}' | cut -c1-300 ;;
 stop)  call '{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"stop_game","arguments":{}}}' | cut -c1-300 ;;
 input) call '{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"send_input","arguments":'"$2"'}}' | cut -c1-300 ;;      # raw send_input arguments (JSON)
 key)   call '{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"send_input","arguments":{"type":"key","key":"'"$2"'"}}}' | cut -c1-300 ;;
 click) call '{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"send_input","arguments":{"type":"mouse_button","button":"'"${4:-left}"'","x":'"$2"',"y":'"$3"'}}}' | cut -c1-300 ;;
 gameshot) rm -f "screenshots/$2.tga"     # game view incl. HUD; the Game View window must be visible
        call '{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"make_game_screenshot","arguments":{"path":"screenshots/'"$2"'.tga"}}}' | grep -o '"message":"[^"]*"'
        for i in $(seq 1 30); do sleep 1; [ -s "screenshots/$2.tga" ] && break; done; sleep 2
        "$B/blender.exe" --background --python tools/tga2png.py -- "$(pwd -W)/screenshots/$2.tga" "$(pwd -W)/screenshots/$2.png" "${3:-0.6}" 2>&1 | grep -E "SAVED|Error" ;;
 shot)  rm -f "screenshots/$2.tga"
        call '{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"make_screenshot","arguments":{"path":"screenshots/'"$2"'.tga"}}}' > /dev/null
        for i in $(seq 1 30); do sleep 1; [ -s "screenshots/$2.tga" ] && break; done; sleep 2      # the TGA is written asynchronously
        "$B/blender.exe" --background --python tools/tga2png.py -- "$(pwd -W)/screenshots/$2.tga" "$(pwd -W)/screenshots/$2.png" "${3:-0.6}" 2>&1 | grep -E "SAVED|Error" ;;
esac
