#!/bin/bash
# Spawns a small station of modules generated by scripts/modgen.evox in the Studio scene (not the game: no orbit frame, no resources).
# Usage: tools/preview_station.sh X Y Z [SEED]      X Y Z = engine position of the central module
cd "$(dirname "$0")/.."; X=${1:-0}; Y=${2:-0}; Z=${3:-0}; S=${4:-1}
at() { awk -v x=$X -v y=$Y -v z=$Z -v a=$1 -v b=$2 -v c=$3 'BEGIN{printf "%.2f %.2f %.2f", x+a, y+b, z+c}'; }
m() { bash tools/parts_demo.sh module "$1" $((S * 31 + $1)) --at $(at $2 $3 $4) "${@:5}" | grep -v '"isError":false'; true; }
m 0 0 0 0                        # central
m 1 6.1 0 0 --keep               # habitat on +X
m 2 -6.1 0 0 --keep              # hydroponics on -X
m 9 0 0 -5.6 --yaw 90 --keep     # junction on -Z
m 8 0 0 7.1 --yaw 90 --keep      # greenhouse on +Z
m 3 0 0 -9.3 --yaw 90 --keep     # research lab on the junction's far end
m 6 3.6 0 -5.6 --keep            # battery bank on a junction side port
m 5 -4.1 0 -5.6 --keep           # storage on the other
m 10 0 1.12 -5.6 --up --keep     # solar wing on the junction's top pad
m 12 0 -1.12 -5.6 --down --keep  # gas storage underneath
