"""Low-level helpers for the parts kits (Blender 5.x), used through parts_lib.py: sheet layout lookup (rect / SW / FIT / STRIP), the Builder (faces, boxes,
revolved rings mapped onto the sheet), vertex AO bake, the sheet material, FBX export, sockets / collision helpers and the preview render.
The sheet is generated by make_parts_sheet.py into models/parts_sheet/."""
import bpy, bmesh, json, math, random, time
from pathlib import Path
from mathutils import Vector, Matrix
from mathutils.bvhtree import BVHTree
ROOT=Path('C:/projects/space_game'); SHEET=ROOT/'models/parts_sheet'; TEX=SHEET/'textures'
LAY=json.loads((SHEET/'parts_layout.json').read_text()); S=LAY['size']; RECTS=LAY['rects_xywh_from_top']
AXI={'x':0,'y':1,'z':2}

def rect(name):
    x,y,w,h=RECTS[name]; return x/S,1-(y+h)/S,(x+w)/S,1-y/S
def SW(name): return (name,'swatch',None)
def FIT(name,ua='x'): return (name,'fit',ua)
def STRIP(name,ua='x'): return (name,'strip',ua)
def frame_of(axis,sg):
    if axis=='x': return Vector((sg,0,0)),Vector((0,1,0)),Vector((0,0,1))
    if axis=='y': return Vector((0,sg,0)),Vector((1,0,0)),Vector((0,0,1))
    return Vector((0,0,sg)),Vector((1,0,0)),Vector((0,1,0))
def rot(*cols): return Matrix(cols).transposed()

class Builder:
    def __init__(s,seed=3):
        s.bm=bmesh.new(); s.uv=s.bm.loops.layers.uv.new('UV0'); s.rng=random.Random(seed)
    def face(s,pts,uvs,out=None,smooth=False,mat=0):
        pts=[Vector(p) for p in pts]; uvs=list(uvs)
        if out is not None:
            n=(pts[1]-pts[0]).cross(pts[2]-pts[0])
            if n.dot(out)<0: pts.reverse(); uvs.reverse()
        try: f=s.bm.faces.new([s.bm.verts.new(p) for p in pts])
        except ValueError: return None
        for l,uv in zip(f.loops,uvs): l[s.uv].uv=uv
        f.smooth=smooth; f.material_index=mat; return f
    def spec_uv(s,spec,tu,tv,ulen):
        name,kind,_=spec; u0,v0,u1,v1=rect(name)
        if kind=='swatch': return ((u0+u1)/2,(v0+v1)/2)
        if kind=='fit': return (u0+tu*(u1-u0),v0+tv*(v1-v0))
        eps=1.0/S; span=min((u1-u0),max(ulen/4.0,.02))           # 4 m per sheet width
        return (s._us+tu*span, v0+eps+tv*(v1-v0-2*eps))
    def box(s,c,size,R=None,maps=None,default=SW('SW_DARK')):
        R=R or Matrix.Identity(3); h=[size[0]/2,size[1]/2,size[2]/2]; c=Vector(c); maps=maps or {}
        for k,ax in enumerate('xyz'):
            for sg in (-1,1):
                spec=maps.get(('+' if sg>0 else '-')+ax,maps.get(ax,default)); a,b=[i for i in range(3) if i!=k]
                ua=spec[2]; s._us=s.rng.uniform(0,max(0,1-(2*h[AXI[ua]] if ua else 0)/4.0)) if spec[1]=='strip' else 0
                pts=[];uvs=[]
                for ca,cb in [(-1,-1),(1,-1),(1,1),(-1,1)]:
                    l=[0,0,0]; l[k]=sg*h[k]; l[a]=ca*h[a]; l[b]=cb*h[b]
                    pts.append(c+R@Vector(l)); ta,tb=(ca+1)/2,(cb+1)/2
                    if ua and AXI[ua]==b: tu,tv,ul=tb,ta,2*h[b]
                    else: tu,tv,ul=ta,tb,(2*h[a] if ua else 1)
                    uvs.append(s.spec_uv(spec,tu,tv,ul))
                unit=[0,0,0]; unit[k]=sg; s.face(pts,uvs,R@Vector(unit))
    def revolve(s,origin,n,T1,T2,profile,segs,rscale=1.0):
        """profile: [(r,h,strip)] outer->inner; the strip wraps the circumference"""
        for (r0,h0,_),(r1,h1,strip) in zip(profile[:-1],profile[1:]):
            r0*=rscale; r1*=rscale
            if abs(r0-r1)<1e-6 and abs(h0-h1)<1e-6: continue
            u0,v0,u1,v1=rect(strip); eps=1.0/S; wall=abs(r0-r1)<1e-6
            for i in range(segs):
                ta,tb=2*math.pi*i/segs,2*math.pi*(i+1)/segs
                ra=T1*math.cos(ta)+T2*math.sin(ta); rb=T1*math.cos(tb)+T2*math.sin(tb); rm=(ra+rb).normalized()
                A=origin+n*h0+ra*r0; B=origin+n*h0+rb*r0; C=origin+n*h1+rb*r1; D=origin+n*h1+ra*r1
                ua,ub=u0+(u1-u0)*i/segs,u0+(u1-u0)*(i+1)/segs; va,vb=v0+eps,v1-eps
                out=rm*(h1-h0)+n*(-(r1-r0))
                if r1<1e-6: s.face([A,B,origin+n*h1],[(ua,va),(ub,va),((ua+ub)/2,vb)],out)
                else: s.face([A,B,C,D],[(ua,va),(ub,va),(ub,vb),(ua,vb)],out,smooth=wall)
    def quad_spec(s,pts,spec,out,ulen=1):
        """single quad mapped as a box face would be (pts in order 0,1,2,3 = (0,0),(1,0),(1,1),(0,1))"""
        s._us=s.rng.uniform(0,max(0,1-ulen/4.0))
        s.face(pts,[s.spec_uv(spec,tu,tv,ulen) for tu,tv in [(0,0),(1,0),(1,1),(0,1)]],out)

def ao_bake(b,samples=28,dist=.5):
    bm=b.bm; bm.faces.ensure_lookup_table(); bm.normal_update(); bvh=BVHTree.FromBMesh(bm); rnd=random.Random(5)
    layer=bm.loops.layers.float_color.new('AO'); base=[]
    for i in range(samples):
        r1=(i+.5)/samples; ang=i*2.399963; rr=math.sqrt(r1); base.append((rr*math.cos(ang),rr*math.sin(ang),math.sqrt(1-r1)))
    for f in bm.faces:
        n=f.normal; t=n.orthogonal().normalized(); bt=n.cross(t); r=rnd.uniform(0,6.283); cs,sn=math.cos(r),math.sin(r)
        dirs=[(t*(x*cs-y*sn)+bt*(x*sn+y*cs)+n*z).normalized() for x,y,z in base]
        for l in f.loops:
            p=l.vert.co+n*.004; hit=sum(1 for d in dirs if bvh.ray_cast(p,d,dist)[0] is not None)
            v=1-hit/samples; v=.3+.7*v**.85; l[layer]=(v,v,v,1.0)

def make_object(name,builder):
    ao_bake(builder); me=bpy.data.meshes.new(name); builder.bm.to_mesh(me)
    ob=bpy.data.objects.new(name,me); bpy.context.scene.collection.objects.link(ob); me.validate(); me.update(); return ob

def make_material(name='parts_trim',prefix='parts',tex_dir=None):
    m=bpy.data.materials.new(name); m.use_nodes=True; nt=m.node_tree
    for n in list(nt.nodes):
        if n.bl_idname!='ShaderNodeOutputMaterial': nt.nodes.remove(n)
    out=next(n for n in nt.nodes if n.bl_idname=='ShaderNodeOutputMaterial'); p=nt.nodes.new('ShaderNodeBsdfPrincipled')
    def tex(fname,color,loc):
        img=bpy.data.images.load(str((tex_dir or TEX)/fname)); img.colorspace_settings.name='sRGB' if color else 'Non-Color'   # left unpacked so FBX/GLB export reference the files
        n=nt.nodes.new('ShaderNodeTexImage'); n.image=img; n.location=loc; return n
    bc=tex(prefix+'_basecolor.png',True,(-900,400)); bc.name='BASECOLOR_TEX'; nm=tex(prefix+'_normal.png',False,(-900,-100)); orm=tex(prefix+'_orm.png',False,(-900,150)); em=tex(prefix+'_emissive.png',True,(-900,-400))
    ca=nt.nodes.new('ShaderNodeVertexColor'); ca.layer_name='AO'; ca.location=(-900,650)
    mix=nt.nodes.new('ShaderNodeMix'); mix.name='AO_MULTIPLY'; mix.data_type='RGBA'; mix.blend_type='MULTIPLY'; mix.inputs['Factor'].default_value=1; mix.location=(-500,450)
    nt.links.new(bc.outputs['Color'],mix.inputs['A']); nt.links.new(ca.outputs['Color'],mix.inputs['B']); nt.links.new(mix.outputs['Result'],p.inputs['Base Color'])
    nmn=nt.nodes.new('ShaderNodeNormalMap'); nmn.uv_map='UV0'; nmn.location=(-500,-100)
    nt.links.new(nm.outputs['Color'],nmn.inputs['Color']); nt.links.new(nmn.outputs['Normal'],p.inputs['Normal'])
    sep=nt.nodes.new('ShaderNodeSeparateColor'); sep.location=(-500,150); nt.links.new(orm.outputs['Color'],sep.inputs['Color'])
    nt.links.new(sep.outputs['Green'],p.inputs['Roughness']); nt.links.new(sep.outputs['Blue'],p.inputs['Metallic'])
    nt.links.new(em.outputs['Color'],p.inputs['Emission Color']); p.inputs['Emission Strength'].default_value=5
    group=bpy.data.node_groups.new('glTF Material Output','ShaderNodeTree'); group.interface.new_socket(name='Occlusion',in_out='INPUT',socket_type='NodeSocketFloat')
    go=nt.nodes.new('ShaderNodeGroup'); go.node_tree=group; go.location=(-200,-300); nt.links.new(sep.outputs['Red'],go.inputs['Occlusion'])
    nt.links.new(p.outputs['BSDF'],out.inputs['Surface']); return m

def link_base(mat,with_ao):
    """FBX/GLB exporters only write an albedo texture when the image node feeds Base Color directly, so export with with_ao=False
    (the vertex AO still ships as COLOR_0); use with_ao=True for Blender preview renders."""
    nt=mat.node_tree; p=next(n for n in nt.nodes if n.bl_idname=='ShaderNodeBsdfPrincipled')
    for l in list(p.inputs['Base Color'].links): nt.links.remove(l)
    src=nt.nodes['AO_MULTIPLY'].outputs['Result'] if with_ao else nt.nodes['BASECOLOR_TEX'].outputs['Color']
    nt.links.new(src,p.inputs['Base Color'])

def select(objs):
    bpy.ops.object.select_all(action='DESELECT')
    for o in objs: o.hide_set(False); o.select_set(True)
    bpy.context.view_layer.objects.active=objs[0]
def export_extras(path,objs,materials=True):
    """FBX is the only mesh format we ship (no GLB). materials=True: the visual mesh is exported by export_fbx, so here we only write its socket
    empties to <stem>.sockets.json (name, location, outward normal, interface kind). materials=False: the objects are collision proxies -> <stem>.fbx."""
    path=Path(path)
    if materials:
        info={}
        for o in objs:
            if o.type=='EMPTY':
                n=o.matrix_world.to_3x3()@Vector((0,0,1)); info[o.name]={'location':[round(v,4) for v in o.location],'normal':[round(v,4) for v in n],'interface':o.get('interface','')}
        (path.parent/(path.stem+'.sockets.json')).write_text(json.dumps(info,indent=1))
    else:
        select(objs); bpy.ops.export_scene.fbx(filepath=str(path.parent/(path.stem+'.fbx')),use_selection=True,apply_scale_options='FBX_SCALE_UNITS',axis_forward='-Z',axis_up='Y',
                                               path_mode='AUTO',embed_textures=False,mesh_smooth_type='FACE',use_tspace=False)
def export_fbx(path,ob):
    select([ob]); props=bpy.ops.export_scene.fbx.get_rna_type().properties
    bpy.ops.export_scene.fbx(filepath=str(path),use_selection=True,apply_scale_options='FBX_SCALE_UNITS',axis_forward='-Z',axis_up='Y',path_mode='RELATIVE',embed_textures=False,mesh_smooth_type='FACE',use_tspace=True)
def socket(name,loc,n,kind='docking'):
    e=bpy.data.objects.new(name,None); bpy.context.scene.collection.objects.link(e); e.location=loc
    e.rotation_euler=n.to_track_quat('Z','Y').to_euler(); e.empty_display_size=.1; e['interface']=kind; return e
def collision_box(name,loc,dims):
    bpy.ops.mesh.primitive_cube_add(size=1,location=loc); o=bpy.context.object; o.name=name; o.dimensions=dims; bpy.ops.object.transform_apply(scale=True); return o
def collision_cyl(name,loc,n,r,depth):
    bpy.ops.mesh.primitive_cylinder_add(vertices=12,radius=r,depth=depth,location=loc); o=bpy.context.object; o.name=name
    o.rotation_euler=n.to_track_quat('Z','Y').to_euler(); bpy.ops.object.transform_apply(rotation=True,scale=True); return o
def preview(path,cam_loc,lens=55,target=(0,0,0),res=(1400,1200)):
    scene=bpy.context.scene
    world=bpy.data.worlds.new('space'); scene.world=world; world.use_nodes=True
    bg=next(n for n in world.node_tree.nodes if n.bl_idname=='ShaderNodeBackground'); bg.inputs['Color'].default_value=(.008,.014,.024,1); bg.inputs['Strength'].default_value=.5
    def area(name,loc,power,size,color):
        l=bpy.data.lights.new(name,'AREA'); l.energy=power; l.size=size; l.color=color; o=bpy.data.objects.new(name,l); scene.collection.objects.link(o); o.location=loc
        o.rotation_euler=(Vector(target)-o.location).to_track_quat('-Z','Y').to_euler()
    area('key',(3,-4,6),950,5,(1,.86,.69)); area('rim',(-4,1,3),1150,4,(.52,.75,1)); area('fill',(-2,-5,0),450,4,(1,1,1))
    cam=bpy.data.objects.new('cam',bpy.data.cameras.new('cam')); scene.collection.objects.link(cam); scene.camera=cam
    cam.location=cam_loc; cam.data.lens=lens; cam.rotation_euler=(Vector(target)-cam.location).to_track_quat('-Z','Y').to_euler()
    scene.render.engine='CYCLES'; scene.cycles.samples=48; scene.cycles.use_denoising=True; scene.render.resolution_x,scene.render.resolution_y=res
    scene.render.filepath=str(path); bpy.ops.render.render(write_still=True)
def tri_count(ob): ob.data.calc_loop_triangles(); return len(ob.data.loop_triangles)
